import Image from "next/image";

export default function Home() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-between p-8">
      <h1 className="mb-16 text-3xl font-light uppercase text-center">
        Female Gaze Model
      </h1>
      <h2 className="mb-4 text-2xl font-medium uppercase text-center">
        Portfolio
      </h2>
      <p className="mb-8 text-sm font-light text-center">
        In this gallery you can see a selection of my work. I hope you'll enjoy.
      </p>
      <div className="flex flex-col gap-4">
        <Image
          src="https://femalegaze.pages.dev/photo100.jpg"
          alt=""
          width="640"
          height="640"
        />
        <Image
          src="https://femalegaze.pages.dev/photo200.jpg"
          alt=""
          width="640"
          height="640"
        />
        <Image
          src="https://femalegaze.pages.dev/photo300.jpg"
          alt=""
          width="640"
          height="640"
        />
        <Image
          src="https://femalegaze.pages.dev/photo400.jpg"
          alt=""
          width="640"
          height="640"
        />
        <Image
          src="https://femalegaze.pages.dev/photo500.jpg"
          alt=""
          width="640"
          height="640"
        />
        <Image
          src="https://femalegaze.pages.dev/photo600.jpg"
          alt=""
          width="640"
          height="640"
        />
        <Image
          src="https://femalegaze.pages.dev/photo700.jpg"
          alt=""
          width="640"
          height="640"
        />
        <Image
          src="https://femalegaze.pages.dev/photo800.jpg"
          alt=""
          width="640"
          height="640"
        />
        <Image
          src="https://femalegaze.pages.dev/photo900.jpg"
          alt=""
          width="640"
          height="640"
        />
        <Image
          src="https://femalegaze.pages.dev/photo1000.jpg"
          alt=""
          width="640"
          height="640"
        />
        <Image
          src="https://femalegaze.pages.dev/photo1100.jpg"
          alt=""
          width="640"
          height="640"
        />
        <Image
          src="https://femalegaze.pages.dev/photo1200.jpg"
          alt=""
          width="640"
          height="640"
        />
        <Image
          src="https://femalegaze.pages.dev/photo1300.jpg"
          alt=""
          width="640"
          height="640"
        />
        <Image
          src="https://femalegaze.pages.dev/photo1400.jpg"
          alt=""
          width="640"
          height="640"
        />
        <Image
          src="https://femalegaze.pages.dev/photo1500.jpg"
          alt=""
          width="640"
          height="640"
        />
        <Image
          src="https://femalegaze.pages.dev/photo1600.jpg"
          alt=""
          width="640"
          height="640"
        />
        <Image
          src="https://femalegaze.pages.dev/photo1700.jpg"
          alt=""
          width="640"
          height="640"
        />
        <Image
          src="https://femalegaze.pages.dev/photo1800.jpg"
          alt=""
          width="640"
          height="640"
        />
        <Image
          src="https://femalegaze.pages.dev/photo1900.jpg"
          alt=""
          width="640"
          height="640"
        />
        <Image
          src="https://femalegaze.pages.dev/photo2000.jpg"
          alt=""
          width="640"
          height="640"
        />
        <Image
          src="https://femalegaze.pages.dev/photo2100.jpg"
          alt=""
          width="640"
          height="640"
        />
        <Image
          src="https://femalegaze.pages.dev/photo2200.jpg"
          alt=""
          width="640"
          height="640"
        />
        <Image
          src="https://femalegaze.pages.dev/photo2300.jpg"
          alt=""
          width="640"
          height="640"
        />
        <Image
          src="https://femalegaze.pages.dev/photo2400.jpg"
          alt=""
          width="640"
          height="640"
        />
        <Image
          src="https://femalegaze.pages.dev/photo2500.jpg"
          alt=""
          width="640"
          height="640"
        />
        <Image
          src="https://femalegaze.pages.dev/photo2600.jpg"
          alt=""
          width="640"
          height="640"
        />
        <Image
          src="https://femalegaze.pages.dev/photo2700.jpg"
          alt=""
          width="640"
          height="640"
        />
        <Image
          src="https://femalegaze.pages.dev/photo2800.jpg"
          alt=""
          width="640"
          height="640"
        />
      </div>
    </main>
  );
}
