import Image from "next/image";

export default function Home() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-between p-8">
      <h1 className="mb-16 text-3xl font-light uppercase text-center">
        Female Gaze Model
      </h1>
      <h2 className="mb-4 text-2xl font-medium uppercase text-center">
        Portfolio
      </h2>
      <p className="mb-8 text-sm font-light text-center">
        In this gallery you can see a selection of my work. I hope you'll enjoy.
      </p>
      <div className="flex flex-col gap-4">
        <Image
          src="https://femalegaze.pages.dev/100.jpg"
          alt=""
          width="640"
          height="640"
        />
        <Image
          src="https://femalegaze.pages.dev/200.jpg"
          alt=""
          width="640"
          height="640"
        />
        <Image
          src="https://femalegaze.pages.dev/300.jpg"
          alt=""
          width="640"
          height="640"
        />
        <Image
          src="https://femalegaze.pages.dev/400.jpg"
          alt=""
          width="640"
          height="640"
        />
        <Image
          src="https://femalegaze.pages.dev/500.jpg"
          alt=""
          width="640"
          height="640"
        />
        <Image
          src="https://femalegaze.pages.dev/600.jpg"
          alt=""
          width="640"
          height="640"
        />
        <Image
          src="https://femalegaze.pages.dev/700.jpg"
          alt=""
          width="640"
          height="640"
        />
        <Image
          src="https://femalegaze.pages.dev/800.jpg"
          alt=""
          width="640"
          height="640"
        />
        <Image
          src="https://femalegaze.pages.dev/900.jpg"
          alt=""
          width="640"
          height="640"
        />
        <Image
          src="https://femalegaze.pages.dev/1000.jpg"
          alt=""
          width="640"
          height="640"
        />
        <Image
          src="https://femalegaze.pages.dev/1100.jpg"
          alt=""
          width="640"
          height="640"
        />
        <Image
          src="https://femalegaze.pages.dev/1200.jpg"
          alt=""
          width="640"
          height="640"
        />
        <Image
          src="https://femalegaze.pages.dev/1300.jpg"
          alt=""
          width="640"
          height="640"
        />
        <Image
          src="https://femalegaze.pages.dev/1400.jpg"
          alt=""
          width="640"
          height="640"
        />
        <Image
          src="https://femalegaze.pages.dev/1500.jpg"
          alt=""
          width="640"
          height="640"
        />
        <Image
          src="https://femalegaze.pages.dev/1600.jpg"
          alt=""
          width="640"
          height="640"
        />
        <Image
          src="https://femalegaze.pages.dev/1700.jpg"
          alt=""
          width="640"
          height="640"
        />
        <Image
          src="https://femalegaze.pages.dev/1800.jpg"
          alt=""
          width="640"
          height="640"
        />
        <Image
          src="https://femalegaze.pages.dev/1900.jpg"
          alt=""
          width="640"
          height="640"
        />
        <Image
          src="https://femalegaze.pages.dev/2000.jpg"
          alt=""
          width="640"
          height="640"
        />
        <Image
          src="https://femalegaze.pages.dev/2100.jpg"
          alt=""
          width="640"
          height="640"
        />
        <Image
          src="https://femalegaze.pages.dev/2200.jpg"
          alt=""
          width="640"
          height="640"
        />
        <Image
          src="https://femalegaze.pages.dev/2300.jpg"
          alt=""
          width="640"
          height="640"
        />
        <Image
          src="https://femalegaze.pages.dev/2400.jpg"
          alt=""
          width="640"
          height="640"
        />
        <Image
          src="https://femalegaze.pages.dev/2500.jpg"
          alt=""
          width="640"
          height="640"
        />
        <Image
          src="https://femalegaze.pages.dev/2600.jpg"
          alt=""
          width="640"
          height="640"
        />
        <Image
          src="https://femalegaze.pages.dev/2700.jpg"
          alt=""
          width="640"
          height="640"
        />
        <Image
          src="https://femalegaze.pages.dev/2800.jpg"
          alt=""
          width="640"
          height="640"
        />
        <Image
          src="https://femalegaze.pages.dev/2900.jpg"
          alt=""
          width="640"
          height="640"
        />
        <Image
          src="https://femalegaze.pages.dev/3000.jpg"
          alt=""
          width="640"
          height="640"
        />
        <Image
          src="https://femalegaze.pages.dev/3100.jpg"
          alt=""
          width="640"
          height="640"
        />
        <Image
          src="https://femalegaze.pages.dev/3200.jpg"
          alt=""
          width="640"
          height="640"
        />
        <Image
          src="https://femalegaze.pages.dev/3300.jpg"
          alt=""
          width="640"
          height="640"
        />
        <Image
          src="https://femalegaze.pages.dev/3400.jpg"
          alt=""
          width="640"
          height="640"
        />
        <Image
          src="https://femalegaze.pages.dev/3500.jpg"
          alt=""
          width="640"
          height="640"
        />
        <Image
          src="https://femalegaze.pages.dev/3600.jpg"
          alt=""
          width="640"
          height="640"
        />
        <Image
          src="https://femalegaze.pages.dev/3700.jpg"
          alt=""
          width="640"
          height="640"
        />
      </div>
      <p className="my-16 font-extralight italic">
        <q>Art can never exist without naked beauty displayed.</q> – William
        Blake
      </p>
    </main>
  );
}
